import { AssetCategory, LiabilityCategory, InsuranceCategory, ItemType } from '../types';

export interface CategorySuggestion {
  suggestedCategory: AssetCategory | LiabilityCategory | InsuranceCategory;
  suggestedType: ItemType;
  confidence: 'high' | 'medium' | 'low';
  matchedKeyword: string;
  matchedRule?: string;
}

export interface KeywordCategoryMapping {
  keywords: string[];
  suggestedCategory: AssetCategory | LiabilityCategory | InsuranceCategory;
  suggestedType: ItemType;
  confidence: 'high' | 'medium' | 'low';
  description: string;
}

/**
 * Keyword Mapping Dictionary for auto-categorization of manual ledger items.
 * Ordered by precedence (Insurance policies -> Specific Liabilities -> Specific Assets -> Broader Cash/Investments).
 */
export const KEYWORD_CATEGORY_DICTIONARY: KeywordCategoryMapping[] = [
  // --- Insurance Policies ---
  {
    keywords: [
      'whole life',
      'cash value life',
      'permanent life',
    ],
    suggestedCategory: 'Whole Life Insurance',
    suggestedType: 'insurance',
    confidence: 'high',
    description: 'Whole Life insurance policies',
  },
  {
    keywords: [
      'universal life',
      'variable universal',
      'indexed universal',
      'iul',
    ],
    suggestedCategory: 'Universal Life Insurance',
    suggestedType: 'insurance',
    confidence: 'high',
    description: 'Universal Life insurance policies',
  },
  {
    keywords: [
      'disability insurance',
      'long term disability',
      'short term disability',
      'ltd policy',
      'guardian disability',
    ],
    suggestedCategory: 'Disability Insurance',
    suggestedType: 'insurance',
    confidence: 'high',
    description: 'Disability insurance coverage',
  },
  {
    keywords: [
      'health insurance',
      'long-term care',
      'long term care',
      'ltc insurance',
      'medicare supplement',
    ],
    suggestedCategory: 'Health & Long-Term Care',
    suggestedType: 'insurance',
    confidence: 'high',
    description: 'Health & Long-Term Care insurance',
  },
  {
    keywords: [
      'umbrella policy',
      'umbrella insurance',
      'liability umbrella',
      'property insurance',
      'homeowners policy',
      'hazard policy',
    ],
    suggestedCategory: 'Property & Umbrella',
    suggestedType: 'insurance',
    confidence: 'high',
    description: 'Property & Umbrella liability coverage',
  },
  {
    keywords: [
      'term life',
      'life insurance',
      'death benefit',
      'policy coverage',
      'prudential',
      'northwestern mutual',
      'new york life',
      'metlife',
      'lincoln financial',
      'massmutual',
      'pacific life',
      'guardian life',
    ],
    suggestedCategory: 'Term Life Insurance',
    suggestedType: 'insurance',
    confidence: 'high',
    description: 'Term Life Insurance and general death benefits',
  },

  // --- Liabilities & Debts ---
  {
    keywords: [
      'mortgage',
      'home loan',
      'housing loan',
      'house loan',
      'rocket mortgage',
      'fannie mae',
      'freddie mac',
      'quicken loans',
      'pennymac',
      'mr cooper',
      'wells fargo mortgage',
      'chase mortgage',
      'primary mortgage',
      'secondary mortgage',
    ],
    suggestedCategory: 'Mortgage',
    suggestedType: 'liability',
    confidence: 'high',
    description: 'Home mortgage and real estate debt',
  },
  {
    keywords: [
      'credit card',
      'visa',
      'mastercard',
      'amex',
      'american express',
      'sapphire',
      'freedom',
      'card balance',
      'apple card',
      'discover card',
      'discover it',
      'citi double',
      'citi custom',
      'capital one venture',
      'capital one quicksilver',
      'chase sapphire',
      'barclays card',
      'credit line',
    ],
    suggestedCategory: 'Credit Cards',
    suggestedType: 'liability',
    confidence: 'high',
    description: 'Credit cards and revolving charge accounts',
  },
  {
    keywords: [
      'student loan',
      'student loans',
      'nelnet',
      'edfinancial',
      'navient',
      'aidvantage',
      'mohela',
      'tuition loan',
      'sallie mae',
      'great lakes',
      'fafsa loan',
      'stafford loan',
      'direct unsubsidized',
      'direct subsidized',
    ],
    suggestedCategory: 'Student Loans',
    suggestedType: 'liability',
    confidence: 'high',
    description: 'Student and higher-education loans',
  },
  {
    keywords: [
      'auto loan',
      'car loan',
      'vehicle loan',
      'car finance',
      'car lease',
      'honda financial',
      'toyota financial',
      'ford credit',
      'tesla finance',
      'gm financial',
      'bmw financial',
      'hyundai motor finance',
      'nissan finance',
      'ally auto',
    ],
    suggestedCategory: 'Auto Loans',
    suggestedType: 'liability',
    confidence: 'high',
    description: 'Automobile and vehicle loans',
  },
  {
    keywords: [
      'personal loan',
      'sofi loan',
      'lendingclub',
      'prosper loan',
      'upstart',
      'marcus loan',
      'best egg',
      'debt consolidation',
      'installment loan',
      'unsecured loan',
      'line of credit',
      'heloc',
      'home equity line',
    ],
    suggestedCategory: 'Personal Loans',
    suggestedType: 'liability',
    confidence: 'high',
    description: 'Personal loans, HELOCs, and credit lines',
  },
  {
    keywords: [
      'loan',
      'debt',
      'payable',
      'liability',
      'owe',
      'borrowed',
      'promissory note',
      'tax debt',
      'irs payment plan',
      'medical debt',
    ],
    suggestedCategory: 'Other Liabilities',
    suggestedType: 'liability',
    confidence: 'medium',
    description: 'General debts and liabilities',
  },

  // --- Assets: Retirement ---
  {
    keywords: [
      '401k',
      '401(k)',
      'ira',
      'roth',
      'roth ira',
      'traditional ira',
      'sep ira',
      'simple ira',
      'pension',
      '403b',
      '403(b)',
      '457',
      '457b',
      'superannuation',
      'retirement',
      'tsp',
      'thrift savings',
      'vanguard target retirement',
      'fidelity freedom',
    ],
    suggestedCategory: 'Retirement (401k/IRA)',
    suggestedType: 'asset',
    confidence: 'high',
    description: 'Tax-advantaged retirement accounts and pensions',
  },

  // --- Assets: Crypto ---
  {
    keywords: [
      'crypto',
      'bitcoin',
      'btc',
      'ethereum',
      'eth',
      'binance',
      'coinbase',
      'solana',
      'sol',
      'cardano',
      'ada',
      'wallet',
      'ledger nano',
      'trezor',
      'kraken',
      'metamask',
      'phantom wallet',
      'coldcard',
      'ripple',
      'xrp',
      'usdt',
      'usdc',
      'polygon',
      'matic',
      'avalanche',
      'avax',
      'dogecoin',
      'doge',
      'chainlink',
      'uniswap',
    ],
    suggestedCategory: 'Crypto',
    suggestedType: 'asset',
    confidence: 'high',
    description: 'Cryptocurrencies and digital assets',
  },

  // --- Assets: Real Estate ---
  {
    keywords: [
      'real estate',
      'primary home',
      'primary residence',
      'rental property',
      'investment property',
      'condo',
      'apartment',
      'townhouse',
      'house',
      'home equity',
      'land',
      'vacation home',
      'commercial real estate',
      'duplex',
      'triplex',
      'fourplex',
      'zillow',
      'redfin',
      'villa',
      'flat',
      'reit',
    ],
    suggestedCategory: 'Real Estate',
    suggestedType: 'asset',
    confidence: 'high',
    description: 'Real estate, homes, and properties',
  },

  // --- Assets: Precious Metals ---
  {
    keywords: [
      'gold',
      'silver',
      'platinum',
      'palladium',
      'bullion',
      'krugerrand',
      'pamp',
      'ingot',
      'gold bar',
      'silver bar',
      'gold coin',
      'silver eagle',
      'maple leaf coin',
      'oz gold',
      'oz silver',
      'precious metal',
    ],
    suggestedCategory: 'Precious Metals',
    suggestedType: 'asset',
    confidence: 'high',
    description: 'Gold, silver, and precious metals bullion',
  },

  // --- Assets: Bonds & Fixed Income ---
  {
    keywords: [
      'bond',
      'bonds',
      'treasury',
      'treasuries',
      't-bill',
      'tbill',
      't-note',
      't-bond',
      'tips',
      'fixed income',
      'muni',
      'municipal bond',
      'corporate bond',
      'i-bond',
      'ibond',
      'series i',
      'series ee',
      'us treasury',
      'bnd',
      'agg',
    ],
    suggestedCategory: 'Bonds & Fixed Income',
    suggestedType: 'asset',
    confidence: 'high',
    description: 'Government bonds, treasuries, and fixed-income assets',
  },

  // --- Assets: Vehicle & Physical ---
  {
    keywords: [
      'car',
      'auto',
      'vehicle',
      'truck',
      'suv',
      'motorcycle',
      'tesla',
      'toyota',
      'honda',
      'ford',
      'bmw',
      'mercedes',
      'porsche',
      'audi',
      'watch',
      'rolex',
      'patek',
      'audemars',
      'omega watch',
      'jewelry',
      'diamond',
      'boat',
      'yacht',
      'rv',
      'camper',
    ],
    suggestedCategory: 'Vehicle & Physical',
    suggestedType: 'asset',
    confidence: 'medium',
    description: 'Automobiles, luxury goods, and physical valuables',
  },

  // --- Assets: Alternative & Private ---
  {
    keywords: [
      'startup',
      'venture capital',
      'private equity',
      'hedge fund',
      'angel investment',
      'syndicate',
      'private company',
      'convertible note',
      'safe note',
      'equity ownership',
      'art collection',
      'rare wine',
      'collectibles',
    ],
    suggestedCategory: 'Alternative & Private',
    suggestedType: 'asset',
    confidence: 'medium',
    description: 'Private equity, venture, and alternative investments',
  },

  // --- Assets: Stocks & ETFs ---
  {
    keywords: [
      'stock',
      'stocks',
      'etf',
      'etfs',
      'share',
      'shares',
      'equity',
      'equities',
      'vanguard',
      'fidelity',
      'schwab',
      'charles schwab',
      'robinhood',
      'e*trade',
      'etrade',
      'td ameritrade',
      'interactive brokers',
      'ibkr',
      'webull',
      'm1 finance',
      'wealthfront',
      'betterment',
      'acorns',
      's&p',
      's&p 500',
      'sp500',
      'nasdaq',
      'dow jones',
      'total stock',
      'index fund',
      'mutual fund',
      'voo',
      'vti',
      'qqq',
      'spy',
      'vt',
      'schd',
      'vug',
      'brokerage',
      'trading account',
      'portfolio',
    ],
    suggestedCategory: 'Stocks & ETFs',
    suggestedType: 'asset',
    confidence: 'high',
    description: 'Equities, ETFs, index funds, and brokerage accounts',
  },

  // --- Assets: Cash & Equivalents ---
  {
    keywords: [
      'checking',
      'savings',
      'cash',
      'bank',
      'hysa',
      'high yield savings',
      'money market',
      'mma',
      'certificate of deposit',
      'cd account',
      'revolut',
      'wise',
      'chase checking',
      'chase savings',
      'wells fargo',
      'bank of america',
      'bofa',
      'citibank',
      'capital one 360',
      'marcus',
      'ally bank',
      'discover bank',
      'sofi checking',
      'sofi savings',
      'deposit',
      'emergency fund',
      'petty cash',
      'safe deposit',
      'paypal balance',
      'venmo balance',
    ],
    suggestedCategory: 'Cash & Equivalents',
    suggestedType: 'asset',
    confidence: 'high',
    description: 'Checking, savings, money market, and liquid cash',
  },
];

/**
 * Heuristic auto-categorization engine that matches an account/item name against
 * the keyword mapping dictionary to infer the appropriate category and type.
 */
export function suggestCategoryFromAccountName(
  accountName: string,
): CategorySuggestion | null {
  if (!accountName || accountName.trim().length < 2) {
    return null;
  }

  const text = accountName.toLowerCase().trim();

  // Search keyword mappings in dictionary order
  for (const mapping of KEYWORD_CATEGORY_DICTIONARY) {
    for (const keyword of mapping.keywords) {
      // Check for exact substring match or word boundary match
      if (text.includes(keyword)) {
        return {
          suggestedCategory: mapping.suggestedCategory,
          suggestedType: mapping.suggestedType,
          confidence: mapping.confidence,
          matchedKeyword: keyword,
          matchedRule: mapping.description,
        };
      }
    }
  }

  return null;
}
